### ISSUE TITLE
changing tool offsets changes Probed axis limits

### ISSUE THREAD

**Issue by martijnschouten** [diabase/H-Series-Configuration#13]
I ran into the issue that the changing the tool offsets seems to change the Probed axis limits seemingly randomly. The changes are small, but they seem to add up if a lot of adjustments are done and gave me offsets of about half a millimeter after a calibration. The following procedure reproduces the error for me:
1. Home the printer
2. measure Z on the offsets tab; config-override.g -> M208 S0 Z193.96
3. T2
4. increase x-offset of T2 by 0.01mm in the offset tab; config-override.g -> M208 S0 Z193.98
5. T3
6. increase x-offset of T3 by 0.01mm in the offset tab; config-override.g -> M208 S0 Z193.92

**Comment by RonaldThomas** [comment]
Hi Martijn,
I think we've identified cause of this issue and we've pushed the fix to your branch. 

Tool changes occurring within 40mm of the z-axis end stop were prompting an update of the maximum z-axis limit as detected by the activation of the z-axis limit switch. This updated position is then committed to config-override.g when modifications are made to the tool offsets. The z-axis movement speed during tool changes was fast enough to produce a small variance between the expected and actual positions on the z-axis when the limit switch is triggered. As you discovered, an accumulation of these small variances results in a non-trivial position error.

With commit e36f999, the z hop performed during tool changes is now moves only to the previously defined axis limit instead of triggering the limit switch and updating it.

This commit will also be included in the next release.
